### PR TITLE
Add optional customizable role name and description

### LINKED ISSUE #40: Add an optional input variable to name the role
# 💡 Summary #

Add an optional input variable to name the role

## Motivation and context ##

We have identified a valid use case where multiple roles for reading the same certificate should exist.   When one assessment is mostly completed, but the infrastructure (namely the cert-reading role) for that assessment has not been destroyed, it is desirable to use that same domain (and cert) in another assessment environment.  As it currently stands, this use case cannot be supported because the new environment attempts to create a role with the same name as one that already exists (from the first assessment).  If we could supply a name to the role when we create it, we could avoid that problem.

## Implementation notes ##

See [cisagov/s3-read-role-tf-module](https://github.com/cisagov/s3-read-role-tf-module) where we do something similar.

## Acceptance criteria ##

- [ ] The cert-read-role can be given a custom name.
- [ ] If no name is given, the cert-read-role defaults to the name that we currently use.

### PR DESCRIPTION
**Pull request by dav3r**
#  #

## 🗣 Description ##

This PR adds the ability to optionally give the role a custom name and/or description.

## 💭 Motivation and context ##

From #40:
> We have identified a valid use case where multiple roles for reading the same certificate should exist. When one assessment is mostly completed, but the infrastructure (namely the cert-reading role) for that assessment has not been destroyed, it is desirable to use that same domain (and cert) in another assessment environment. As it currently stands, this use case cannot be supported because the new environment attempts to create a role with the same name as one that already exists (from the first assessment). If we could supply a name to the role when we create it, we could avoid that problem.

Resolves #40.

## 🧪 Testing ##

I successfully applied the example terraform using the two new variables.  I also ran several test `terraform plan`s to ensure that these new variables are working as expected.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - _eschew scope creep!_
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by mcdonnnj — APPROVED** [review]
Makes sense. My only addition is that it might make sense to document the way the new variables are interpreted (if `%s` are found use `format()`, otherwise use it as-is).

**Review by jsf9k — APPROVED** [review]

**Comment by dav3r** [comment]
> Makes sense. My only addition is that it might make sense to document the way the new variables are interpreted (if `%s` are found use `format()`, otherwise use it as-is).

@mcdonnnj I thought I sufficiently did that in https://github.com/cisagov/cert-read-role-tf-module/pull/41/commits/90ace0854d6570d7ac600983e7d86e40073449d6#.  Can you please clarify where else you'd like to see that documented?

**Comment by mcdonnnj** [comment]
> > Makes sense. My only addition is that it might make sense to document the way the new variables are interpreted (if `%s` are found use `format()`, otherwise use it as-is).
> 
> @mcdonnnj I thought I sufficiently did that in [90ace08](https://github.com/cisagov/cert-read-role-tf-module/commit/90ace0854d6570d7ac600983e7d86e40073449d6). Can you please clarify where else you'd like to see that documented?

@dav3r The variable descriptions do not mention the alternate behavior if the requisite number of `%s` are not in the given value. The comments in `locals.tf` excellently explain the behavior, but you'd have to dig into the configuration to find this undocumented functionality.

**Comment by dav3r** [comment]
> @dav3r The variable descriptions do not mention the alternate behavior if the requisite number of `%s` are not in the given value. The comments in `locals.tf` excellently explain the behavior, but you'd have to dig into the configuration to find this undocumented functionality.

@mcdonnnj Thanks for clarifying, now I understand.  Please let me know if https://github.com/cisagov/cert-read-role-tf-module/pull/41/commits/44686e6c53aa9a708337bafc186bd0cc4872045f scratches that itch.

**Comment by mcdonnnj** [comment]
> > @dav3r The variable descriptions do not mention the alternate behavior if the requisite number of `%s` are not in the given value. The comments in `locals.tf` excellently explain the behavior, but you'd have to dig into the configuration to find this undocumented functionality.
> 
> @mcdonnnj Thanks for clarifying, now I understand. Please let me know if [44686e6](https://github.com/cisagov/cert-read-role-tf-module/commit/44686e6c53aa9a708337bafc186bd0cc4872045f) scratches that itch.

@dav3r Excellent! Looks great to me 👍

**Pull request merged**
